# Generated by Django 3.2.13 on 2022-06-15 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(null=True, upload_to='productos'),
        ),
        migrations.AddField(
            model_name='producto',
            name='peso',
            field=models.FloatField(default=(0), max_length=5),
            preserve_default=False,
        ),
    ]
